parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $routePrefix: '%app.security.api_route%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Model/'
            - '../src/Dto/'
            - '../src/Kernel.php'
